import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../services/api.js';

const display = (value) => String(value || '').replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
export default function AdminDashboardPage() {
  const [data, setData] = useState(null); const [message, setMessage] = useState('Loading dashboard…');
  useEffect(() => { api.get('/admin/dashboard').then(({ data: result }) => { setData(result); setMessage(''); }).catch((error) => setMessage(error.response?.data?.message || 'Unable to load dashboard.')); }, []);
  if (!data) return <main className="p-6 text-slate-600 sm:p-10">{message}</main>;
  const { metrics, recentOrders } = data;
  const cards = [['Total orders', metrics.totalOrders], ['Pending payment', metrics.pendingOrders], ['In progress', metrics.inProgress], ['Completed', metrics.completed], ['Customers', metrics.customers], ['Partners', metrics.partners], ["Today's orders", metrics.todayOrders], ['Total revenue', `₹${metrics.totalRevenue}`]];
  return <main className="p-5 sm:p-10"><p className="text-sm font-bold uppercase tracking-wider text-blue-700">Admin overview</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Dashboard</h1><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value]) => <article key={label} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></article>)}</div><section className="mt-7 grid gap-4 md:grid-cols-2"><article className="rounded-xl bg-blue-700 p-6 text-white"><p className="text-sm text-blue-100">Customer revenue</p><p className="mt-2 text-3xl font-bold">₹{metrics.customerRevenue}</p></article><article className="rounded-xl bg-slate-900 p-6 text-white"><p className="text-sm text-slate-300">Partner revenue</p><p className="mt-2 text-3xl font-bold">₹{metrics.partnerRevenue}</p></article></section><section className="mt-7 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="flex items-center justify-between p-5"><h2 className="font-bold text-slate-900">Recent orders</h2><Link className="text-sm font-semibold text-blue-700" to="/admin/orders">View all</Link></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">Order</th><th className="px-5 py-3">Buyer</th><th className="px-5 py-3">Service</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{recentOrders.map((order) => <tr key={order.id} className="border-t border-slate-100"><td className="px-5 py-4 font-semibold">{order.orderNumber}</td><td className="px-5 py-4">{order.buyer}</td><td className="px-5 py-4">{order.service}</td><td className="px-5 py-4">₹{order.amount}</td><td className="px-5 py-4">{display(order.orderStatus)}</td></tr>)}{recentOrders.length === 0 && <tr><td colSpan="5" className="px-5 py-8 text-center text-slate-500">No orders yet.</td></tr>}</tbody></table></div></section></main>;
}
