import { useEffect, useState } from 'react';
import { ArrowRight, BadgeCheck, BriefcaseBusiness, FileText, GraduationCap, IdCard, Landmark, MessageCircle, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../services/api.js';

const icons = [FileText, IdCard, GraduationCap, Landmark, BriefcaseBusiness];
const steps = [['1', 'Sign Up / Login', 'Create your account as a customer or partner.'], ['2', 'Choose a Service', 'Select what you need from our list.'], ['3', 'Make Payment', 'Pay securely online.'], ['4', 'Get WhatsApp Contact', 'Send documents directly to us.'], ['5', 'Work in Progress', 'Track completion from your dashboard.']];

export default function HomePage() {
  const [services, setServices] = useState([]);
  useEffect(() => { api.get('/services/public').then(({ data }) => setServices(data.services.slice(0, 5))).catch(() => setServices([])); }, []);
  return <main className="bg-[#faf8f4] text-[#102d2a]"><section className="relative isolate min-h-[530px] overflow-hidden rounded-b-[2.5rem] px-5 pb-12 pt-14 sm:min-h-[590px] sm:pt-20"><img src="/brand/hero.png" alt="E CAFE HIMACHAL digital service workspace in Himachal Pradesh" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-white/95 via-white/68 to-white/10"/><div className="relative mx-auto max-w-6xl"><p className="inline-flex items-center gap-2 rounded-full bg-white/70 px-4 py-2 text-sm font-semibold backdrop-blur"><BadgeCheck size={16} className="text-[#276052]"/> E CAFE HIMACHAL</p><h1 className="mt-5 max-w-3xl text-4xl font-extrabold tracking-tight text-slate-950 sm:text-6xl">Digital Services,<br/><span className="text-[#276052]">Online Support & Opportunities</span></h1><p className="mt-4 max-w-xl text-base leading-7 text-slate-700 sm:text-lg">A Himachal-focused network for jobs, forms, education, digital services, business growth and partner support.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/customer/register" className="inline-flex items-center gap-2 rounded-full bg-[#143f3a] px-6 py-3 font-bold text-white shadow-lg shadow-[#143f3a]/20 hover:bg-[#0c2f2a]">Get Started <ArrowRight size={18}/></Link><Link to="/services" className="rounded-full bg-white/90 px-6 py-3 font-semibold text-slate-700 shadow-sm hover:bg-white">Explore Services</Link></div><div className="mt-10 flex gap-5 text-sm sm:gap-8"><Stat value="55+" label="Official Services"/><Stat value="Himachal" label="Focused Network"/><Stat value="100%" label="Transparent Fees"/></div></div><div className="relative mx-auto mt-12 max-w-6xl sm:mt-10"><div className="ml-auto max-w-[260px] rounded-2xl bg-white/90 p-4 text-sm shadow-xl backdrop-blur"><div className="flex gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#e1f0ed] text-[#276052]"><ShieldCheck size={21}/></div><p className="font-medium text-slate-700">Use official and authorized platforms. Fees are communicated clearly.</p></div></div></div></section>
  <section className="mx-auto max-w-6xl px-5 pt-7"><div className="rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 text-sm leading-6 text-amber-950"><strong>Important notice:</strong> eCafeHimachal is a private digital service platform. It is not a government website and is not affiliated with, endorsed by, or officially connected to any government department or authority.</div></section>
  <section className="mx-auto max-w-6xl px-5 py-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="inline-flex rounded-full bg-[#e5eee8] px-3 py-1 text-sm font-semibold text-[#143f3a]">Our Services</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-slate-950">Popular Services</h2><p className="mt-2 text-slate-600">Simple, fast and reliable help for everyday online work.</p></div><Link to="/services" className="inline-flex items-center gap-2 font-semibold text-[#143f3a]">View All Services <ArrowRight size={18}/></Link></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{services.map((service, index) => { const Icon = icons[index % icons.length]; const shades = ['bg-sky-50', 'bg-emerald-50', 'bg-rose-50', 'bg-violet-50', 'bg-amber-50']; return <Link to="/services" key={service.id} className={`group min-h-56 rounded-2xl border border-black/5 p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg ${shades[index % shades.length]}`}><span className="flex h-14 w-14 items-center justify-center rounded-full bg-white/70 text-[#276052]"><Icon size={28}/></span><h3 className="mt-7 font-bold text-slate-900">{service.name}</h3><p className="mt-2 text-sm leading-5 text-slate-600">{service.description}</p><span className="mt-5 inline-flex rounded-full bg-white/70 p-2 transition group-hover:translate-x-1"><ArrowRight size={17}/></span></Link>; })}{services.length === 0 && <p className="text-slate-600">Services are loading. Please refresh in a moment.</p>}</div></section>
  <section id="how-it-works" className="mx-auto max-w-6xl px-5 pb-16"><p className="inline-flex rounded-full bg-[#f1efd8] px-3 py-1 text-sm font-semibold text-[#143f3a]">Simple Process</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-slate-950">How It Works</h2><p className="mt-2 text-slate-600">Get your work done in just a few simple steps.</p><div className="mt-8 grid gap-4 md:grid-cols-5">{steps.map(([number, title, description]) => <article key={number} className="rounded-xl bg-white/70 p-4"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#276052] text-sm font-bold text-white">{number}</span><h3 className="mt-4 text-sm font-bold text-slate-900">{title}</h3><p className="mt-1 text-sm leading-5 text-slate-600">{description}</p></article>)}</div><div className="mt-8 flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-[#143f3a] p-7 text-white"><div><h2 className="text-2xl font-bold">Run a cyber cafe?</h2><p className="mt-1 text-sm text-emerald-50">Partner with us for expert online service support.</p></div><Link to="/partner/register" className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 font-bold text-[#143f3a]"><MessageCircle size={18}/> Become a Partner</Link></div></section></main>;
}
function Stat({ value, label }) { return <div className="border-r border-slate-500/30 pr-5 last:border-0"><p className="text-2xl font-extrabold text-slate-950">{value}</p><p className="text-xs font-medium text-slate-700">{label}</p></div>; }
